// MEMBER
export const INSTANTIATE_MEMBER = 'INSTANTIATE_MEMBER';
export const SET_MEMBER_NAME = 'SET_MEMBER_NAME';

// ASSETS
export const CREATE_ASSET = 'CREATE_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
